version: '3'

services:
    reverse-proxy:
        container_name: reverse-proxy
        # The official v2.0 Traefik docker image
        image: traefik:v2.0
        command:
            - "--global.sendanonymoususage=false"
            - "--api.insecure=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.file=true"
            - "--providers.file.filename=/etc/traefik/providers-config.toml"
            - "--certificatesresolvers.myhttpchallenge=true"
            - "--certificatesresolvers.myhttpchallenge.acme.email=${ACME_EMAIL}"
            - "--certificatesresolvers.myhttpchallenge.acme.storage=/etc/traefik/ssl/acme.json"
            - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
            - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
        restart: always
        environment:
            HA_ADDRESS:
            HA_DOMAIN_NAME:
        ports:
            - 80:80
            - 443:443
            # The Web UI (enabled by --api)
            - 8080:8080
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-config:/etc/traefik
        logging:
            options:
                max-size: 10m

    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi2-homeassistant:0.103.0
        volumes:
            - homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro
            - /var/run/restartd_signal:/var/run/restartd_signal
        restart: always
        network_mode: host
        ports:
            - 8123:8123
        depends_on:
            - mosquitto
        extra_hosts:
            - "mysql:192.168.11.10"
            - "mosquitto:192.168.11.10"
        logging:
            options:
                max-size: 10m

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-config:/mosquitto/config
        restart: always
        ports:
            - 1883:1883
        extra_hosts:
            - "homeassistant:192.168.11.10"
        logging:
            options:
                max-size: 10m

    nodered:
        container_name: nodered
        image: nodered/node-red
        volumes:
            - nodered-data:/data
        restart: always
        depends_on:
            - mosquitto
        ports:
            - 1880:1880
        extra_hosts:
            - "homeassistant:192.168.11.10"
        logging:
            options:
                max-size: 10m
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nodered.rule=Host(`${HA_DOMAIN_NAME}`) && PathPrefix(`/red`)"
            - "traefik.http.routers.nodered.entrypoints=websecure"
            - "traefik.http.routers.nodered.tls=true"
            - "traefik.http.routers.nodered-insecure.rule=Host(`${HA_DOMAIN_NAME}`) && PathPrefix(`/red`)"
            - "traefik.http.routers.nodered-insecure.entrypoints=web"
            - "traefik.http.routers.nodered-insecure.middlewares=redirecthttps@file"

volumes:
    traefik-config:
        external: true
    homeassistant-config:
        external: true
    mosquitto-data:
        external: true
    mosquitto-config:
        external: true
    nodered-data:
        external: true
