version: '3'

services:
    homeassistant:
        container_name: home-assistant
        image: homeassistant/raspberrypi2-homeassistant:0.95.1
        volumes:
            - homeassistant-config:/config
            - /etc/localtime:/etc/localtime:ro
        restart: always
        network_mode: host
        depends_on:
            - mosquitto
        extra_hosts:
            - "mysql:192.168.11.10"
            - "mosquitto:192.168.11.10"
        logging:
            options:
                max-size: 10m

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        volumes:
            - mosquitto-data:/mosquitto/data
            - mosquitto-config:/mosquitto/config
        restart: always
        ports:
            - 1883:1883
        logging:
            options:
                max-size: 10m

    nodered:
        container_name: nodered
        image: nodered/node-red-docker:rpi-v8
        volumes:
            - nodered-data:/data
        restart: always
        depends_on:
            - mosquitto
        ports:
            - 1880:1880
        logging:
            options:
                max-size: 10m

volumes:
    homeassistant-config:
        external: true
    mosquitto-data:
        external: true
    mosquitto-config:
        external: true
    nodered-data:
        external: true
